server {
  listen       8080;
  server_name  localhost;
  server_tokens off;
  
  root   /usr/share/nginx/html;
  index  index.html;

  gzip on;
  gzip_static on;
  gzip_vary on;
  gzip_proxied any;
  gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;

  include security-headers.conf;

  location / {
    try_files $uri $uri/ /index.html;
    add_header "Access-Control-Allow-Methods" "GET, POST, DELETE, OPTIONS, PATCH, PUT";
    add_header "Access-Control-Allow-Headers" "Content-Type, Authorization";
    add_header "Access-Control-Allow-Credentials" "true";
  }

  # The root index.html is served for page not found / 404 errors which allows
  # us to use pushState() based routing
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }

  location /health {
    access_log off;
    default_type text/plain;
    return 200 "OK";
  }

  location /app-config {
    add_header Content-Type application/json;
    include security-headers.conf;
    return 200 '{
      "VITE_BACKEND_URL": "${VITE_BACKEND_URL}"
    }\n';
  }
}