# With Content Security Policy (CSP) enabled, we tell the browser that it can
# only load content from the domains we explicitly allow.
add_header Content-Security-Policy "default-src 'self' ${VITE_BACKEND_URL}";

# With the Report-To header we get a way to specify server endpoints for the
# browser to send warnings and errors to. 
add_header Report-To "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://cardlay.report-uri.com/a/d/g\"}],\"include_subdomains\":true}";

# With HSTS (HTTP Strict Transport Security) enabled, we tell browsers that the
# app should only be accessed using HTTPS, instead of using HTTP.
# 
# It’s difficult to back out of an HSTS policy in order to remove the HTTPS
# version of a website or service. When we test HSTS, we use a very short
# max-age timeout and ensure we’re comfortable with the effects. When we go live
# with the HSTS policy, we keep max-age small and increase it only when we're
# confident about doing so. (https://hstspreload.org/)
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# Included nosniff, it prevents the browser from doing MIME-type sniffing. 
add_header X-Content-Type-Options nosniff;